name: release

on:
  push:
    tags:
      - '*'

jobs:
  create-release-draft:
    name: Create GitHub Release Draft
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: npm
      - run: npm install
      - run: npm run build
      - name: Release
        uses: softprops/action-gh-release@v1
        draft: true
        with:
          files: |
             wasm/bazel-bin/lyra-wasm/lyra.wasm
             wasm/bazel-bin/lyra-wasm/lyra.worker.js

  notification:
    name: Slack Notification
    runs-on: ubuntu-latest
    needs:
      - create-release-draft
    if: always()
    steps:
      - uses: actions/checkout@v3
      - uses: rtCamp/action-slack-notify@v2
        if: |
          needs.create-release-draft.result == 'failure'
        env:
          SLACK_CHANNEL: sora-oss
          SLACK_COLOR: danger
          SLACK_TITLE: Failure release
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
